### ISSUE TITLE
.to_pandas() required in tutorial notebook when writing snap_df

### ISSUE THREAD

**Issue by jeffreybreen** [ranaroussi/pystore#13]
`snap_df` is a `pystore.item.Item`:

`snap_df = collection.item('AAPL', snapshot='snapshot_name')`

but I think `collection.write()` takes a pandas DataFrame instead, so I get an error when I try to run this line:

```
collection.write('AAPL', snap_df,
                 metadata={'source': 'Quandl'},
                 overwrite=True)
```

Adding `.to_pandas()` fixes it:

```
collection.write('AAPL', snap_df.to_pandas(),
                 metadata={'source': 'Quandl'},
                 overwrite=True)
```

**Comment by ranaroussi** [comment]
I've fixed the issue in the recent version and you no longer need to use the ``.to_pandas()`` part :)
