### ISSUE TITLE
Collection list_items()

### ISSUE THREAD

**Issue by cevans3098** [ranaroussi/pystore#20]
Ran,

I have two proposed ideas regarding the list_items():

1. In the collection object I notice that you currently initialize the `self.items = self.list_items()`.  The `self.list_items()` is called. Calling `self.list_items` is unnecessary overhead if you have thousands of items in the collection.  It seems like the `self.items` can be updated directly without searching the directory again. Can we just remove the item from the list or add it too the list

2. Do you see value in changing the type of `self.items` from a list to a set?  Since the items in the collection are unique, this seems like a valid option and the search speed would be considerably faster.

If these changes are of interest I can do a PR.  Let me know

Craig

**Comment by ranaroussi** [comment]
Hi Craig,

1. I've implemented ``collection.items`` and ``collection.snapshots`` as ``@property`` so they can still be called the same way, but with the added benifit of reduced overhead upon initialization.

2. ``collection.items`` and ``collection.snapshots`` are now of type ``set()``.

Thanks for the feedback :)

**Comment by cevans3098** [comment]
Ran,

Thanks for the updates.  The first point of my question was poorly written.  Calling self.list_items() during __init__ was good and needed to be done.  My question on the overhead was that in the collection.write method the item list/set is refreshed by [calling self.list_items()](https://github.com/ranaroussi/pystore/blob/0fcc8b7fe5199cac0c5905b3c43c4a34d78ec1da/pystore/collection.py#L136).  Can this be accomplished simply by self.items.add(item).  This will eliminate the directory read every time a new item is added.  If new items are added frequently, then the directory has to be read a lot and the self.items variable is recreated a lot

I run into this problem primarily when uploading historical option minute data.  Every contract is a unique item and for a given month I can have thousands of items.  As a result, self.items is recreated thousands of times and the directory is read thousands of times.

As an example, when the collection is empty, I can add more than 50 items per second.  At the end of the first month (5000 new items added), the write rate reduces to 7 items per second.  This rate will reduce further as additional months are added.

**Comment by ranaroussi** [comment]
Got it!

Here's what I did in v0.1.11 (still not on PyPI - get it from Github):

- I brought back `self.list_items()` to the `__init__` method
- In `collection.write(...)`, I'm using `self.items.add(item)` *and* calling `self._list_items_threaded()` to make sure that the data is still being kept up to date if multiple writes occur.
- I've added `collection.write_threaded(...)` for cases when you don't need to access the data right away and can wait for a few ms/s for the data to be written.

Let me know what you think :)

**Comment by cevans3098** [comment]
Ran,

I noticed you kept in [self._list_items_threaded()](https://github.com/ranaroussi/pystore/blob/7043df4a7ac528c8f131719c8c9b2b8dd94da1ee/pystore/collection.py#L142) during the write.  If pystore is the only service maintaining the data, why add this redundancy?  Are you concerned with an outside service modifying the collection?  [Updating the set with the add](https://github.com/ranaroussi/pystore/blob/7043df4a7ac528c8f131719c8c9b2b8dd94da1ee/pystore/collection.py#L141) should be sufficient.  If there is concern with an outside service updating the items it might be better (less overhead) to manually update the list by calling [def list_items(self....)](https://github.com/ranaroussi/pystore/blob/7043df4a7ac528c8f131719c8c9b2b8dd94da1ee/pystore/collection.py#L51) if there is a concern instead of forcing the issue.

I like your suggestion of using the threading, I never used the @multitasking.task before - nice trick.

**Comment by ranaroussi** [comment]
Calling `self._list_items_threaded()` isn't that much of overhead as it runs on a separate process that doesn't slow you down, and it helps keep things in order and "aware".

In your case (using many writes) - I think you'd probably be better off using `collection.write_threaded()`. Am I right?

**Comment by cevans3098** [comment]
Ran,

I already have the collection.write and the collection.append running in a multiprocess environment using ProcessPoolExecutor().

After creating the store and collection objects I create a ProcessPollExecutor() and add data to upload using

'''python
    def __update_pystore_option(self, equity_symbol, contract_symbol, resolution, data, new_metadata={}):
        ''' Adds new option data to the collection.  If the contract item does not exist the item is created
         and the data is added.  Otherwise the item is appended'''

        if contract_symbol not in self.collection.items:
            #timer_start=datetime.now()
            self.collection.write(contract_symbol, data, new_metadata)
            #timer_elapsed = (datetime.now()-timer_start).total_seconds()*1000
        else:                                       
            self.collection.append(contract_symbol, data)

        #print(f'*** Current collection size is {len(self.collection.items)} and and update time was {timer_elapsed} ms/item')
'''

the results are shown below 
*** Current collection size is 2 and and write time was 104.997 ms/item
*** Current collection size is 3883 and and write time was 1326.9089999999999 ms/item

 I am still using the previous version (0.1.9) of the code.  Let me think things over today before I update and try the threaded version

**Comment by cevans3098** [comment]
Ran, 
I updated to version 0.1.11 and tried write_threaded().  While it appeared to work quite well, the items were written to the collection at a rate of 80 items/s.  however, the code still took the same period of time to complete because the code was waiting to close the queued thread - in the background the items were still being written for over 3 minutes... this was also seen with the collection folder updating for 3 minutes after it appear the code had completed execution.

Would you be opposed to adding a flag to the self.write() method which will prevent the call of list_items() during each write.  I would propose:

```
def write(self, item, data, metadata={},
              refresh_list=True,
              npartitions=None, chunksize=None, overwrite=False,
              epochdate=False, compression="snappy", **kwargs):

        if utils.path_exists(self._item_path(item)) and not overwrite:
            raise ValueError("""
                Item already exists. To overwrite, use `overwrite=True`.
                Otherwise, use `<collection>.append()`""")

        if isinstance(data, Item):
            data = data.to_pandas()
        else:
            # work on copy
            data = data.copy()

        if epochdate or "datetime" in str(data.index.dtype):
            data = utils.datetime_to_int64(data)

        if data.index.name == "":
            data.index.name = "index"

        if not isinstance(data, dd.DataFrame):
            if npartitions is None and chunksize is None:
                npartitions = None
                chunksize = int(1e6)

            data = dd.from_pandas(data,
                                  npartitions=npartitions,
                                  chunksize=chunksize)

        dd.to_parquet(data,
                      self._item_path(item, as_string=True),
                      compression=compression,
                      engine='fastparquet', **kwargs)

        utils.write_metadata(utils.make_path(
            self.datastore, self.collection, item), metadata)

        # update items
        self.items.add(item)
        if refresh_list == True: self._list_items_threaded()
       
```

**Comment by ranaroussi** [comment]
Done! 

I've added ``reload_items`` (defaults to ``True``) to ``collection.write()`` and ``collection.delete()`` to explicitly re-read the collection's items' directory.

Hope that helps :)

PS. take a look at issue #17

**Comment by cevans3098** [comment]
Ran,

Thanks. This help a lot.  write time were consistently >50 items/sec.  I'll send you my solution to issue #17 shortly

Craig
