### ISSUE TITLE
Terrible performance on dask=2.2.0

### ISSUE THREAD

**Issue by marchinidavide** [ranaroussi/pystore#22]
Hi everyone,
I noticed that `pystore` unexpectedly started being orders of magnitude slower (running the same script), like minutes to get daily timestamp of a single instrument ...
It seems that `dask=2.2.0` is terribly slow using `snappy` and `engine="fastparquet"` but everything is _great again_ downgrading to `dask=2.1.0`.

@ranaroussi it would be great if you could update us on when things will be fin with latest Dask update :)

Best, 
Davide

**Comment by marchinidavide** [comment]
What is painfully slow is the `collection.item("AAPL")` operation ...

**Comment by SteffenNa** [comment]
Does append work for you when using dask==2.2.0?

**Comment by marchinidavide** [comment]
I had to downgrade to `2.1.0` as with the latest one every `read` operation is very slow.
Didn't try anything than reading with `2.2.0`.

**Comment by ranaroussi** [comment]
I've pushed a new version to the dev branch. It should result in a faster and more consistent behavior when using append. By default, PyStore will aim for partitions of ~99MB each (as per Dask's recommendation).

LMK.

**Comment by ranaroussi** [comment]
Please read this regarding Dask 2.3.0:
https://github.com/ranaroussi/pystore/issues/21#issuecomment-523467142

**Comment by ranaroussi** [comment]
Closing this issue and moving all related discussions to issue https://github.com/ranaroussi/pystore/issues/21.

Please see my comments here: https://github.com/ranaroussi/pystore/issues/21#issuecomment-523467142,  and here: https://github.com/ranaroussi/pystore/issues/21#issuecomment-523833921
