### ISSUE TITLE
access item before it's created causes weird PermissionError

### ISSUE THREAD

**Issue by Hugovdberg** [ranaroussi/pystore#28]
When you try to access an item before you write to it, it causes a PermissionError, at least on windows 10. Because it needs to open the item, it creates the directory for the item but then does not create any of the metadata. This causes the item to get in some limbo state where it appears to exist (It is listed as an item using `collection.list_items()`), but it cannot be accessed. 
It would be more helpful to first check if the requested item exists, and if not raise a meaningful `ValueError`, and not create the directory.

**Comment by ranaroussi** [comment]
Can you share the code you've used?
