### ISSUE TITLE
Append not working

### ISSUE THREAD

**Issue by trbck** [ranaroussi/pystore#3]
Using latest version 0.0.12 the append function does not seem to work nor raises an error 

Initial dataframe's last row: 

`df.tail(2)` 

``` 
Close High Low Open Volume 
2017-12-29 00:00:00+00:00 167.15 168.65 167.05 168.25 364619 
2018-01-02 00:00:00+00:00 167.15 167.7 165.25 167.15 587067 
``` 

Saving and appending: 

``` 
store = pystore.store('mydatastore') 
collection = store.collection('eod') 
last = df[-1:] 
collection.write('symbol', df[:-1], overwrite=True) 
collection.append('symbol', last) 
df = collection.item('symbol').to_pandas() 
df.tail(1) 
``` 

yields: 
``` 
Close High Low Open Volume index 
2017-12-29 167.15 168.65 167.05 168.25 364619 
``` 

At least on my end. What am I doing wrong here?

**Comment by ranaroussi** [comment]
Try using ``df.tail()`` instead of ``df.tail(1)`` which only displays the last record.

**Comment by trbck** [comment]
I know, just wanted to simply highlight that it does not seem to append the last row :)

**Comment by trbck** [comment]
Also the length of the df stays the same. Might this somehow be related to snappy?

**Comment by ranaroussi** [comment]
I can't reproduce this on any of my machines...

Try:

```python
store = pystore.store('mydatastore') 
collection = store.collection('eod') 

# write
collection.write('symbol', df[:-1], overwrite=True) 

# append
collection.append('symbol',  df[-1:] ) 

# read
collection.item('symbol').to_pandas() .tail() 
```

**Comment by trbck** [comment]
Got it. The time offset in the dt index was the reason the append did not work an my end. It works when I strip it from the dt value ("2018-07-13 20:03:00" not "2018-07-13 20:03:00+00:00"). Thanks again!
