### ISSUE TITLE
Parquet is preventing data frame storage

### ISSUE THREAD

**Issue by pkrouse** [ranaroussi/pystore#7]
I tried out pystore, and it is almost perfect for my needs.  However, using parquet in the stack causes an issue with storage.  I have data frames to store, and have no control over the data.  Parquet cannot figure out how to store some of my data frames due to conversion problems.  Since parquet focuses on language-independent storage, the data frames cannot be stored without some conversion. I cannot remember where I read that, but it was while tracking down a problem storing directly with parquet a few days ago.  If pystore is meant as a python-only solution, maybe it would be better to use something like pickle instead?  Just a thought.

**Comment by lionelyoung** [comment]
Is this the issue you're seeing?
`ValueError: Error converting column "Testing" to bytes using encoding UTF8. Original error: bad argument type for built-in operation`

**Comment by ranaroussi** [comment]
What’s the data type you have in the problematic column?

**Comment by lionelyoung** [comment]
I had numeric casted as strings by mistake. I recasted it to floats and
that resolved the error

Not sure about OP though
-- 
Sent from my phone
