### ISSUE TITLE
macOS trouble installing python-snappy

### ISSUE THREAD

**Issue by okomarov** [ranaroussi/pystore#8]
I am on macOS 10.14.2, installed snappy with brew, version `stable 1.1.7` and in a **virtual environment**. 

As reported at the bottom of https://github.com/andrix/python-snappy, you need to install python-snappy as follows:

`CPPFLAGS="-I/usr/local/include -L/usr/local/lib" pip install python-snappy`

Please update readme.

**Comment by ranaroussi** [comment]
Done. Thanks!
